### ISSUE TITLE
CSRF Token missmatch

### ISSUE THREAD

**Issue by ChristianFranke** [InvoiceShelf/docker#10]
**Describe the bug**
I restarted InvoiceShelf once after the installation with docker-compose. Then I could no longer log in. The strange thing is that it is reported that I was successfully logged in.

**Expected behavior**
A successful login with redirection to the dashboard.

**Screenshots**
<img width="415" alt="Bildschirmfoto 2024-05-30 um 13 12 15" src="https://github.com/InvoiceShelf/InvoiceShelf/assets/1424478/9190377a-9e4e-4f8d-96d8-35a6e137eb2d">

**Please complete the following information:**
- InvoiceShelf version: 1.2.2 (release)
- PHP version: 8.2
- Database type and version: MariaDB 10.11.8-MariaDB-ubu2204

**Optional info**
- OS:  [e.g. Ubuntu] MacOS
- Browser: [e.g. chrome, safari] Chrome

**Comment by gdarko** [comment]
Hey @ChristianFranke , @jvgreenaway  - The issue  was due to not setting the `SESSION_DOMAIN` and `SANCTUM_STATEFUL_DOMAINS` in docker-compose. 

I rebuild the images, and you can use the new instructions to set up invoiceshelf. Check the Readme.md.

**Comment by cesardv** [comment]
I am getting the same CSRF Token Mismatch error on a basic sqlite docker setup. I've set the `SESSION_DOMAIN` and `SANCTUM_STATEFUL_DOMAINS` values properly (AFAICT) for my domain (i.e set value to say invoice.mysite.xyz) for both, and still see the issue. Very little was changed from the sample sqlite docker compose file. Can you explain why you think it is?

**Comment by cesardv** [comment]
hmm seems that setting `APP_DEBUG=true` and changing to my correct time zone (America/New_York) for `PHP_TZ` and  `TIMEZONE` allowed me to get past that error, and onto the Domain Verification part of installation...
