### ISSUE TITLE
Create Backup not working error: mysqldump not found using Docker image

### ISSUE THREAD

**Issue by luketanti** [InvoiceShelf/docker#11]
**Describe the bug**

Creating backups from inside the settings menu is not working with error: mysqldump not found

![2024-05-20 07_36_36-InvoiceShelf - Self Hosted Invoicing Platform - Work - Microsoft​ Edge](https://github.com/InvoiceShelf/InvoiceShelf/assets/23320513/deb98ac5-2d1d-4540-8e8d-21fc94d2bfec)

**Please complete the following information:**
- InvoiceShelf version: 1.2.2
- PHP version: 
- Database type and version: [MySQL ](mariadb:10)

**Optional info**
- Docker Environment
- OS:  CoreOS
- Browser: Edge

**Comment by rihards-simanovics** [comment]
related to: https://github.com/InvoiceShelf/docker/issues/29
