### ISSUE TITLE
SQLite not working

### ISSUE THREAD

**Issue by engemil** [InvoiceShelf/docker#12]
I tried to run Invoiceshelf as a container with the following command: `docker run -p 80 invoiceshelf/invoiceshelf`

When I was in the start-up configuration page, and selected sqlite. The path for it was automatically choosen to be `/var/www/html/InvoiceShelf/database/database.sqlite`

Then I pressed Continue and Safe, which threw me this error:

```
Error

Database file at path [/var/www/html/InvoiceShelf/database/database.sqlite] does not exist. Ensure this is an absolute path to the database

```

I entered the container and saw there was no `database.sqlite` in the given directory.

Is it supposed to be generated during startup or are we to provide it?

**Comment by gdarko** [comment]
Hey @engemil ,

The docker image has been reworked to properly support SQLite.

Please use one of the tags: :latest, :1.3.0, :nightly, :alpha depending of what you want in your compose file and restart installation. It should work.

Check the repository readme.md file and the docker compose section.
https://github.com/InvoiceShelf/docker

Best Regards,
Darko
