### ISSUE TITLE
Application settings - shown version not correct?

### ISSUE THREAD

**Issue by Hoschi1982** [InvoiceShelf/docker#14]
**Describe the bug**
I use the current docker image with tag 1.2.2. (the correct image is used)
After pulling the correct image and restart the containers I looked into the application settings where the version 1.1.0 is shown.

**Expected behavior**
When I use the version 1.2.2, I want to see the correct version in the application settings.

Docker Image: invoiceshelf/invoiceshelf:1.2.2

**Comment by gdarko** [comment]
The issue has been resolved with the updated Docker image.

You can re-pull the image again and check.

https://github.com/InvoiceShelf/docker?tab=readme-ov-file#compose-upgrade
