### ISSUE TITLE
Env vars are not read

### ISSUE THREAD

**Issue by parasiteoflife** [InvoiceShelf/docker#19]
I've set up environment variables for the db and the email server but at the initial setup InvoiceShelf still asks me for this data and the corresponding blocks are empty.

**Comment by mchev** [comment]
The installation process doesn't automatically read the .env file. You'll need to provide the required information manually during the initial setup.
It’s not necessary to edit the .env file before starting the installation, as the required information will be provided manually during the initial setup.
https://docs.invoiceshelf.com/install/manual.html

**Comment by rihards-simanovics** [comment]
Asked and answered.
