### ISSUE TITLE
Upgrade from 1.3.0 to 2.0.0

### ISSUE THREAD

**Issue by hari-bo** [InvoiceShelf/docker#20]
I recently attempted to upgrade our Docker image from invoiceshelf/invoiceshelf:1.3.0 to invoiceshelf/invoiceshelf:2.0.0. While the upgrade process itself appeared to complete without any issues, I’ve encountered a problem upon logging into the application. Specifically, I am unable to interact with any of the menu options – clicking on them doesn’t trigger any actions.

Upon checking the logs, I only see standard GET requests, with no error messages or anything out of the ordinary that could point to the issue. This makes troubleshooting difficult since there are no clear indications of what might be going wrong.

Additionally, I reviewed the upgrade documentation for version 2.0.0, and I couldn’t find any mention of changes to environment variables or additional steps that are required post-upgrade. It seems like the upgrade should be straightforward, but something is clearly preventing the application from functioning properly.

Could you provide any guidance on resolving this issue? Are there any undocumented steps or common issues that arise during this upgrade that I might have overlooked?

**Comment by leonidas-o** [comment]
I had that issue too (and others). Right now it seems to work except that the wrong version is still shown in settings `1.3.0` instead `2.0.0`.

What I've done:
Same steps according to the docs
1. Shut down your current environment: `docker compose down`
2. Pull the latest image version: `docker compose pull`
3. Start and rebuild: `docker compose up --force-recreate --build -d`

4. Looked like the migration wasn't executed, so I entered the invoiceshelf container and executed:
`php artisan migrate`

5. Opened new incognito/private browser window, tried to log in, got `These credentials do not match our records`. And in the browsers debug tools, in the console I see: `Failed to load resource: the server responded with a status of 422 ()`.
So I entered the db container `select id, name, email, password, role, created_at, updated_at from users;` and saw that the `updated_at` timestamps was updated, I guess the migration was messing with the password/ hashing.

6. Added the smtp settings to the `.env`, clicked on `forgot password?`, used the reset link to update the password and now  the login was working again.

Login and navigation through all of the menu options should now work again. The only unsolved point is the `1.3.0` in settings. Everything else should work.

**Comment by gdarko** [comment]
Thanks @leonidas-o, i will check this issue.

**Comment by leonidas-o** [comment]
@gdarko okay, thanks.
Entered the container and it shows the correct one:
```bash
cat version.md 
2.0.0
```

**Comment by gdarko** [comment]
Thanks @leonidas-o 

This commit https://github.com/InvoiceShelf/docker/commit/9de4b332ca500a1296cca945372f547f31b43354 fixes the issue. And i just [rebuild the 2.0.0 image](https://github.com/InvoiceShelf/docker/actions/runs/11646298605).

You can clear/prune cache and re-pull the image.

**Comment by leonidas-o** [comment]
I can confirm that stopping the container, re-pulling the image and starting it back up is working. Settings show the correct version `2.0.0` now.

**Comment by gdarko** [comment]
Great - Thanks for bringing this to my attention, @leonidas-o
