### ISSUE TITLE
Can't complete the installation process

### ISSUE THREAD

**Issue by devuar** [InvoiceShelf/docker#23]
I'm trying to install the app with MySQL docker-compose.yml file but it stucks on Installation step:

![Captura de pantalla 2024-10-30 171110](https://github.com/user-attachments/assets/5fbfc192-e742-46a5-be12-c4bc75ef1642)

There are no logs about this error.

Infra:

MySQL 8.4.3 running in Docker. Database has charset by default "utf8mb4_0900_ai_ci". Database User authentication has "Native password authentication" on.

InvoiceShelf:

```dockerfile
services:
  invoiceshelf:
    image: invoiceshelf/invoiceshelf:1.2.2
    container_name: invoiceshelf
    hostname: invoiceshelf
    ports:
      - 9092:80
    volumes:
      - /aplicaciones/facturacion/data:/data
      - /aplicaciones/facturacion/conf:/conf
    networks:
      - aplicaciones
    environment:
      - PHP_TZ=America/Argentina/Buenos_Aires
      - TIMEZONE=UTC-3
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:90
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=invoiceshelf
      - DB_USERNAME=invoiceshelf
      - DB_PASSWORD=xxxxxxxxx
      - DB_PASSWORD_FILE=
      - CACHE_STORE=file
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - SESSION_ENCRYPT=false
      - SESSION_PATH=/
      - SESSION_DOMAIN=localhost
      - SANCTUM_STATEFUL_DOMAINS=localhost:90
      - STARTUP_DELAY=
    restart: always
networks:
  aplicaciones:
    external:
      true
``` 

What am I doing wrong?
Thanks!

**Comment by gdarko** [comment]
Hey @devuar -

Can you please set  version 2.0.0?

Change this:

```
services:
  invoiceshelf:
    image: invoiceshelf/invoiceshelf:1.2.2
```

to this:

```
services:
  invoiceshelf:
    image: invoiceshelf/invoiceshelf:2.0.0
```

There were some known issues that are already resolved.

When trying to re-run the installation:
- Clear the browser cookies 

Also, note that the database host should be `invoiceshelf_db` if you are using the default docker-compose mysql variant.

Hope this helps.

**Comment by devuar** [comment]
Thank you @gdarko for your advice. But the error was the same.
What I found out that my already running MySQL container seems was not compatible. Therefore, had to launch another container but with MariaDB (as was specified in docker-compose.yml file) and all went smooth. My idea was not to have running 2 containers with databases. Well, meanwhile my server has enough RAM...
Thanks.
