### ISSUE TITLE
[bug] Summary returns 403

### ISSUE THREAD

**Issue by Firesphere** [InvoiceShelf/docker#6]
The tax/sales etc. reports return a big dark 403 screen where the PDF is supposed to be.
`"GET /reports/tax-summary/EKVBD0mWlxA6xOA1nPLY?from_date=2024-03-01&to_date=2024-03-31 HTTP/1.0" 403 6622`

**Comment by rihards-simanovics** [comment]
Stale, if issue persists please reopen the issue.
