### ISSUE TITLE
Public storage not symlinked

### ISSUE THREAD

**Issue by Firesphere** [InvoiceShelf/docker#7]
The path for `/storage/something` in the `public` folder of the application isn't symlinked to the storage folder, causing files to not load and requiring a manual symlink to be created.

**Comment by gdarko** [comment]
The issue has been fixed with the most recent image versions :1.3.0, :latest, :alpha, :nightly.

You can follow the upgrade guide:

https://github.com/InvoiceShelf/docker?tab=readme-ov-file#compose-upgrade
