### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'expires_at' in 'field list'

### ISSUE THREAD

**Issue by williamwithin** [InvoiceShelf/docker#9]
When trying to login with the API, I get this error:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'expires_at' in 'field list'

It was fixed upstream here:

https://github.com/InvoiceShelf/InvoiceShelf/issues/34

**Comment by gdarko** [comment]
The latest docker images include this.

You can check the upgrade guide to upgrade to a newer version.

https://github.com/InvoiceShelf/docker?tab=readme-ov-file#compose-upgrade
